repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.4
    hooks:
      - id: golangci-lint
        entry: bash -c 'cd server && golangci-lint run --config .golangci.yml ./...'
        files: ^server/.*\.go$
        pass_filenames: false

  - repo: https://github.com/realm/SwiftLint
    rev: 0.58.2
    hooks:
      - id: swiftlint
        args: [--config, ios/.swiftlint.yml]
